set1=input("enter a values:")
set1=set(set1.split())
set2=input("enter a values:")
set2=set(set2.split())
print("first set  before removing intersection:",set1)
print("second set:",set2)
intersection=set1.intersection(set2)
set1.difference_update(intersection)
print("first set after removing intersection:",set1)
